### ISSUE TITLE
 Unable to load xlOil excel add-in normally

### ISSUE THREAD

**Issue by catbor** [cunnane/xloil#17] opened 2022-11-09 08:13 UTC
Hi, After 'pip install xlOil' and 'xloil install',  When i open Excel , xlOil always ERROR following info：
' [logger] [error] [PluginLoader.cpp:193] Plugin load failed for D:\anaconda3\share\xloil\xlOil_Python.dll: Initialisation failed
Path=C:\Program Files\Microsoft Office\Root\Office16\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;D:\anaconda3;D:\anaconda3\Scripts;D:\anaconda3\Library\bin;C:\Program Files\Google\Chrome\Application;C:\Program Files\Java\jdk-18.0.1.1\\bin;C:\Program Files\Java\jdk-18.0.1.1\\jre\bin;D:\anaconda3\Library\mingw-w64\bin;D:\anaconda3\Library\usr\bin;C:\Users\XXX\AppData\Local\Microsoft\WindowsApps;C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Microsoft Office\root\Client;D:\anaconda3\share\xloil;D:\anaconda3;D:\anaconda3\Library\bin'

My Python Version：3.8.13
pls help me solve this，thks！

**Comment by cunnane** [comment] 2022-11-09 20:35
Nothing stands out here, could you provide the full log as an attachment?
Please set the log level in %appdata%\xloil\xloil.ini to debug or trace
first.  I'm going to be away a few days so it may take a while to get to
sorry...

**Comment by catbor** [comment] 2022-11-28 07:04
Hello Steven，Sorry to see the message late. Here is full log([xlOil.log](https://github.com/cunnane/xloil/files/10101276/xlOil.log))，please check.

**Comment by cunnane** [comment] 2022-12-06 13:24
Ah, this is a straightforward localisation error.  I'll put out a fix soon but in the meantime you should be able to get things working by changing `<your_python>\site-packages\xloil\_core.py` line 44 from:

`keyval = p[start:end].decode('utf-8').split('=')`

to 

`keyval = p[start:end].decode(locale.getpreferredencoding()).split('=')`

Then adding `import locale` to the top of `_core.py`

**Comment by cunnane** [comment] 2022-12-08 09:47
Sorry, the link to xlOil.log is giving me a 404 at the moment, could you repost it?

**Comment by catbor** [comment] 2022-12-09 05:56
> Sorry, the link to xlOil.log is giving me a 404 at the moment, could you repost it?

Sorry, maybe the attachment was not uploaded successfully due to the network problem before, this is my xloil log file([xlOil.log](https://github.com/cunnane/xloil/files/10192164/xlOil.log)）, please help me see what is the problem, thank you.

**Comment by mskz1** [comment] 2022-12-09 07:24
Hi, Steven, I've got same problem.
Thanks in advance

Python 3.8.10
xlOil 0.15.3
Windows10

--------------------------
[2022-12-09 08:55:39.327] [logger] [error] [logging.py:25] Error during _import_and_scan: Traceback (most recent call last):
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\xloil\register.py", line 129, in logged_func
    return func(*args, **kwargs)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\xloil\importer.py", line 115, in _import_and_scan
    result.append(_import_and_scan(m, addin))
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\xloil\importer.py", line 106, in _import_and_scan
    module = importlib.import_module(what)
  File "c:\users\xxxx\appdata\local\programs\python\python38\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\xloil\importer.py", line 183, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\xloil\xloil_ribbon.py", line 172, in <module>
    _python_enviroments = list(_find_python_enviroments().values())
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\xloil\xloil_ribbon.py", line 144, in _find_python_enviroments
    with reg.OpenKey(reg.HKEY_LOCAL_MACHINE, "Software\\Python") as kPythons:
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
--------------------

**Comment by cunnane** [comment] 2022-12-11 12:34
@catbor I've put a fix for the locale in v0.15.4 which is available now.  I can't see your second `xlOil.log`, so I'm not sure if this fixes all your issues.  

@mskz1 I think your problem might be related to issue #16 - it looks like you don't have any registered python distributions under `HKLM\...\Software\Python` which is triggering a FileNotFound.  This should be fixed in v0.15.4, so please check if a pip update fixes this.

**Comment by mskz1** [comment] 2022-12-11 23:30
@cunnane I update to v0.15.4 and the problem is fixed. Thanks!

**Comment by catbor** [comment] 2022-12-12 04:31
> @catbor I've put a fix for the locale in v0.15.4 which is available now. I can't see your second `xlOil.log`, so I'm not sure if this fixes all your issues.
> 
> @mskz1 I think your problem might be related to issue #16 - it looks like you don't have any registered python distributions under `HKLM\...\Software\Python` which is triggering a FileNotFound. This should be fixed in v0.15.4, so please check if a pip update fixes this.

Thanks, the problem is solved, so far it's working smoothly, but I hope to introduce a parameter prompt similar to excel when entering functions, because when there are too many parameters, it is easy to forget which parameter to enter, and it would be nice to allow users to define .py files as buttons, like this picture
![image](https://user-images.githubusercontent.com/59753214/206960547-01e99240-0007-4f07-bb7a-09cb466ec1f2.png)

These are just my suggestions. xloil is cool. Thank you for your contribution and patience in answering my questions.

**Closed** 2022-12-14 12:03 UTC
